### ISSUE TITLE
issue with getting playlist 

### ISSUE THREAD

**Issue by Solution-TV** [ReenigneArcher/web2tv#11]
Hello
im getting this error what should i do to fix ?

root@Ubuntu-1804-bionic-64-minimal ~/web2tv-main # python plutotv.py
hours: 10
offset: -0000
timezone: -0000
xmlFile: plutotv.xml
m3uFile: plutotv.m3u
prefix:
startNumber: 1
keepNumber: False
streamlink: False
xml: False
m3u: False
Loading Grid for PlutoTV
url: https://service-channels.clusters.pluto.tv/v1/guide?start=2021-02-17T23:00:00-00:00&stop=2021-02-18T09:30:00-00:00
Traceback (most recent call last):
  File "plutotv.py", line 219, in <module>
    'channelName': fix(grid['channels'][x]['name']), #name
  File "plutotv.py", line 37, in fix
    text = str(html.escape(text, quote=False).encode('ascii', 'xmlcharrefreplace'))[2:-1] #https://stackoverflow.com/a/1061702/11214013
AttributeError: 'module' object has no attribute 'escape'

**Comment by ReenigneArcher** [comment]
What version of python are you using?

**Comment by Solution-TV** [comment]
> 
> 
> What version of python are you using?

Python 2.7.17 (default, Sep 30 2020, 13:38:04)

**Comment by ReenigneArcher** [comment]
`html.escape` won't work in Python 2.7. Updating to a 3.x version should fix the problem.

Unless you have a very strong reason to use Python 2.7, you really should upgrade as 2.7 is end of life and no longer supported. Additionally you can probably run python 2.7 and python 3.x side by side if you need to.

In Ubuntu I believe your command would be `python3 plutotv.py` ... not an expert on that though as I use Windows mostly where the command is `py -3 plutotv.py`
